import { Experience } from '../../models/Experience'

export const ExperienceList: Experience[] = [
  {
    logoPath: 'altogic.png',
    company: 'Altogic',
    location: 'Job Location: Wilmington, Delaware, United States',
    startDate: 'June 2022',
    endDate: 'March 2023',
    description:
      "I developed applications and wrote articles using Next.js, Vue.js, and React.js at a startup that provides backend-as-a-service products. I also introduced the project to people. In the projects I worked on, I designed all the backend logic myself. The projects I was involved in were Discusy.com and Opinate.io.      ",
    jobTitle: 'Developer Advocate',
    head: 'Technologies used',
    technologies: [
      'MongoDB',
      'Next JS ',
      'Tailwind CSS',
      'Redux.js',
      'React.js',
      'Javascript',
      'Marketing',
      'Article Writing',
      'Search Engine Optimization (SEO)',
    ],
  },
  {
    logoPath: 'vodafone.png',
    company: 'Vodafone',
    location: 'Istanbul, Turkey',
    startDate: 'Work duration: October 2021 -',
    endDate: 'March 2022',
    description:
      "We were providing support and development for the product as an outsource company through the company I worked for, which provided the customer panel for your internet service at Vodafone.",
    jobTitle: 'Full Stack Developer',
    head: 'Technologies used',
    technologies: [
      'MSSQL',
      'Vue js',
      'HTML5',
      'CSS',
      'jQuery',
      'C#',
      '.NET Framework',
      '.NET Core',
      'Model-View-Controller (MVC)',
      'JavaScript',
      'ASP.NET MVC',
    ],
  },
  {
    logoPath: 'labdroids.png',
    company: 'Labdroids Information Technologies',
    location: 'Istanbul, Turkey',
    startDate: 'January 2022',
    endDate: 'June 2022',
    description:
      "I was involved in both backend and frontend development, working on new projects based on customer requirements and updating existing projects to meet current needs. Overall, I played a key role in developing software solutions that met the customers' needs and contributed to the smooth operation of the team.I gained experience in project management, teamwork, and Agile methodology.",
    jobTitle: 'Full Stack Developer',
    head: 'Technologies used',
    technologies: [
      'MSSQL',
      'Vue js',
      'HTML5',
      'CSS',
      'jQuery',
      'C#',
      '.NET Framework',
      '.NET Core',
      'Model-View-Controller (MVC)',
      'JavaScript',
      'ASP.NET MVC',
    ],
  },
]
